apiVersion: apps/v1
kind: Deployment
metadata:
  name: digilians-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digilians-frontend
  template:
    metadata:
      labels:
        app: digilians-frontend
    spec:
      containers:
        - name: frontend
          image: manarelabsi10/digilians-frontend:latest
          ports:
            - containerPort: 80
